/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubjectCrud: typeof import('./src/components/manage/SubjectCrud.vue')['default']
    TestInstanceCrud: typeof import('./src/components/manage/TestInstanceCrud.vue')['default']
    TestInstanceLearnerAnswerTable: typeof import('./src/components/manage/TestInstanceLearnerAnswerTable.vue')['default']
    TestInstanceLearnerCrud: typeof import('./src/components/manage/TestInstanceLearnerCrud.vue')['default']
    TestInstanceQuestionTable: typeof import('./src/components/manage/TestInstanceQuestionTable.vue')['default']
    TestSchemaCrud: typeof import('./src/components/manage/TestSchemaCrud.vue')['default']
    TestSchemaQuestionCrud: typeof import('./src/components/manage/TestSchemaQuestionCrud.vue')['default']
  }
}
