/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/logout': RouteRecordInfo<'/logout', '/logout', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/tests/': RouteRecordInfo<'/tests/', '/tests', Record<never, never>, Record<never, never>>,
    '/tests/[id]/': RouteRecordInfo<'/tests/[id]/', '/tests/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tests/[id]/attempt': RouteRecordInfo<'/tests/[id]/attempt', '/tests/:id/attempt', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tests/[id]/results': RouteRecordInfo<'/tests/[id]/results', '/tests/:id/results', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
