version: '3.5'

services:
  announcement.app:
    container_name: announcement.app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - announcement.postgres

  announcement.postgres:
    container_name: announcement.postgres
    image: postgres:16.1
    environment:
      POSTGRES_USER: announcement
      POSTGRES_PASSWORD: announcement
      POSTGRES_DB: announcement
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

networks:
  announcement.network:
    external: true